export const noticeTemp = [
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
];

export const qnaRequestsTemp = [
  {
    date: "9월 24일 수요일",
    timeSlots: "수1,2,학등★,사문★, 점법",
    name: "채희준",
    description: "(고려대 경영학과)",
    additionalInfo: "원족상담실 (#암순서부터 신청 #문제해설 진술) - 송파점",
    year: 2025,
    month: 10,
    selectedDate: new Date(2025, 9, 15),
  },
  {
    date: "9월 24일 수요일",
    timeSlots: "수1,2,미적★,물1★,생1",
    name: "이동민",
    description: "(한양대 의대)",
    additionalInfo:
      "2층 오른쪽상담실(#암순서부터 신청 #문제해설 진술) - 대치점 전체",
    year: 2025,
    month: 11,
    selectedDate: new Date(2025, 10, 7),
  },
];

export const postsTemp = [
  {
    username: "gy2551",
    timestamp: "2025/9/25 9:7 AM",
    title: "손가락 걸기 1번선지?",
    content: "키모4회인데 1번도 맞다고 볼 수 있지 않나요? 어떻게 생각하시나요?",
    imageSrc: "/images/temp/notice_card_image_1.jpeg",
    avatarSrc: undefined,
    likesCount: 1,
    comments: [
      {
        username: "조예민",
        userTitle: "고려대 행정학과",
        content:
          "<보기>에 주어진 예시에서 '므'의 'ㅇ', '드'의 'ㄱ', '느'의 'ㅗ'로 잘못 발음될 것을 참고해 선처에 적용시켜주시면 됩니다.",
        timestamp: "2025/9/24 3:33 PM",
        avatarSrc: undefined,
      },
    ],
  },
  {
    username: "pvulleur",
    timestamp: "2025/9/23 4:45 PM",
    title: "언매",
    content: "잘못 받을 될 수 있는걸 제가 어떻게 판단해야하는건가요..?",
    imageSrc: "/images/temp/notice_card_image_2.jpeg",
    avatarSrc: undefined,
    likesCount: 0,
    comments: [],
  },
  {
    username: "student123",
    timestamp: "2025/9/22 2:15 PM",
    title: "수학 미적분 문제 질문",
    content:
      "이 문제 풀이 과정에서 막혔습니다. 도함수 구하는 부분에서 실수가 있는 것 같은데 확인 부탁드려요.",
    imageSrc: "/images/temp/notice_card_image_1.jpeg",
    avatarSrc: undefined,
    likesCount: 3,
    comments: [
      {
        username: "김선생",
        userTitle: "서울대 수학과",
        content:
          "이 부분에서 연쇄법칙을 적용할 때 내부함수의 미분을 빼먹으신 것 같습니다. (x²+1)을 미분하면 2x가 나와야 합니다.",
        timestamp: "2025/9/22 3:20 PM",
        avatarSrc: undefined,
      },
      {
        username: "mathhelper",
        userTitle: "연세대 응용수학과",
        content:
          "김선생님 말씀이 맞습니다. 그리고 추가로 상수항 처리도 조심하세요. 단계별로 천천히 계산해보시면 됩니다.",
        timestamp: "2025/9/22 4:10 PM",
        avatarSrc: undefined,
      },
    ],
  },
];

export const requestStatusTemp = [
  {
    id: 1,
    teacher: "채희준",
    hojeom: "송파점",
    date: "9/24",
    hour: "수1,2",
    proposer: "김민수",
    student_affiliation: "고3",
    location: "원족상담실",
    subjects: "수1,2,학등★,사문★, 점법",
  },
  {
    id: 2,
    teacher: "이동민",
    hojeom: "대치점",
    date: "9/25",
    hour: "수3,4",
    proposer: "박서연",
    student_affiliation: "고2",
    location: "2층 오른쪽상담실",
    subjects: "수1,2,미적★,물1★,생1",
  },
  {
    id: 3,
    teacher: "정수한",
    hojeom: "강남점",
    date: "9/26",
    hour: "화5,6",
    proposer: "이준호",
    student_affiliation: "고3",
    location: "3층 상담실A",
    subjects: "화학1,화학2,생물1",
  },
  {
    id: 4,
    teacher: "김영희",
    hojeom: "노원점",
    date: "9/27",
    hour: "목1,2",
    proposer: "최지은",
    student_affiliation: "고1",
    location: "1층 개별상담실",
    subjects: "국어,문학,화작",
  },
  {
    id: 5,
    teacher: "박철수",
    hojeom: "분당점",
    date: "9/28",
    hour: "금3,4",
    proposer: "한승우",
    student_affiliation: "고3",
    location: "4층 그룹스터디실",
    subjects: "영어,영독,영작",
  },
  {
    id: 6,
    teacher: "윤미나",
    hojeom: "일산점",
    date: "9/29",
    hour: "월1,2",
    proposer: "조현우",
    student_affiliation: "고2",
    location: "2층 멘토링실",
    subjects: "수학1,수학2,확통",
  },
  {
    id: 7,
    teacher: "강태훈",
    hojeom: "송파점",
    date: "9/30",
    hour: "화3,4",
    proposer: "신유진",
    student_affiliation: "고3",
    location: "3층 개별지도실",
    subjects: "물리1,물리2",
  },
  {
    id: 8,
    teacher: "장서현",
    hojeom: "대치점",
    date: "10/1",
    hour: "수5,6",
    proposer: "김도현",
    student_affiliation: "고1",
    location: "1층 그룹상담실",
    subjects: "생물1,지구과학1",
  },
  {
    id: 9,
    teacher: "임현수",
    hojeom: "강남점",
    date: "10/2",
    hour: "목1,2",
    proposer: "이소민",
    student_affiliation: "고3",
    location: "4층 스터디룸A",
    subjects: "화학1,화학2",
  },
  {
    id: 10,
    teacher: "오지훈",
    hojeom: "노원점",
    date: "10/3",
    hour: "금5,6",
    proposer: "박준영",
    student_affiliation: "고2",
    location: "2층 토론실",
    subjects: "한국사,세계사",
  },
  {
    id: 11,
    teacher: "한예슬",
    hojeom: "분당점",
    date: "10/4",
    hour: "토1,2",
    proposer: "최민정",
    student_affiliation: "고3",
    location: "3층 집중학습실",
    subjects: "미적분,기하",
  },
  {
    id: 12,
    teacher: "서동현",
    hojeom: "일산점",
    date: "10/5",
    hour: "일3,4",
    proposer: "김나연",
    student_affiliation: "고1",
    location: "1층 상담실B",
    subjects: "영어1,영어회화",
  },
  {
    id: 13,
    teacher: "류정호",
    hojeom: "송파점",
    date: "10/6",
    hour: "월5,6",
    proposer: "정서윤",
    student_affiliation: "고3",
    location: "4층 질의응답실",
    subjects: "국어,문학",
  },
  {
    id: 14,
    teacher: "민경아",
    hojeom: "대치점",
    date: "10/7",
    hour: "화1,2",
    proposer: "안지호",
    student_affiliation: "고2",
    location: "2층 개별상담실",
    subjects: "사회문화,정치와법",
  },
  {
    id: 15,
    teacher: "신재민",
    hojeom: "강남점",
    date: "10/8",
    hour: "수3,4",
    proposer: "홍수아",
    student_affiliation: "고3",
    location: "3층 멘토링룸",
    subjects: "경제,사회문화",
  },
  {
    id: 16,
    teacher: "배수진",
    hojeom: "노원점",
    date: "10/9",
    hour: "목5,6",
    proposer: "강민석",
    student_affiliation: "고1",
    location: "1층 그룹스터디실",
    subjects: "통합과학,통합사회",
  },
  {
    id: 17,
    teacher: "김다은",
    hojeom: "분당점",
    date: "10/10",
    hour: "금1,2",
    proposer: "윤채원",
    student_affiliation: "고3",
    location: "4층 개별지도실",
    subjects: "확률과통계,미적분",
  },
  {
    id: 18,
    teacher: "조민혁",
    hojeom: "일산점",
    date: "10/11",
    hour: "토3,4",
    proposer: "서준호",
    student_affiliation: "고2",
    location: "2층 질의응답실",
    subjects: "물리1,화학1",
  },
  {
    id: 19,
    teacher: "전하늘",
    hojeom: "송파점",
    date: "10/12",
    hour: "일1,2",
    proposer: "김예은",
    student_affiliation: "고3",
    location: "3층 상담실A",
    subjects: "생명과학1,생명과학2",
  },
  {
    id: 20,
    teacher: "황지원",
    hojeom: "대치점",
    date: "10/13",
    hour: "월3,4",
    proposer: "이동훈",
    student_affiliation: "고1",
    location: "1층 멘토링실",
    subjects: "영어1,영어독해",
  },
  {
    id: 21,
    teacher: "문석진",
    hojeom: "강남점",
    date: "10/14",
    hour: "화5,6",
    proposer: "박지영",
    student_affiliation: "고3",
    location: "4층 토론실",
    subjects: "언어와매체,화법과작문",
  },
  {
    id: 22,
    teacher: "나윤서",
    hojeom: "노원점",
    date: "10/15",
    hour: "수1,2",
    proposer: "최원준",
    student_affiliation: "고2",
    location: "2층 집중학습실",
    subjects: "지구과학1,지구과학2",
  },
  {
    id: 23,
    teacher: "구본우",
    hojeom: "분당점",
    date: "10/16",
    hour: "목3,4",
    proposer: "정민아",
    student_affiliation: "고3",
    location: "3층 개별상담실",
    subjects: "윤리와사상,생활과윤리",
  },
  {
    id: 24,
    teacher: "송하은",
    hojeom: "일산점",
    date: "10/17",
    hour: "금5,6",
    proposer: "김태현",
    student_affiliation: "고1",
    location: "1층 스터디룸B",
    subjects: "한국지리,세계지리",
  },
  {
    id: 25,
    teacher: "이준석",
    hojeom: "송파점",
    date: "10/18",
    hour: "토1,2",
    proposer: "오수빈",
    student_affiliation: "고3",
    location: "4층 질의응답실",
    subjects: "수학1,수학2,미적분",
  },
  {
    id: 26,
    teacher: "최아름",
    hojeom: "대치점",
    date: "10/19",
    hour: "일3,4",
    proposer: "한지우",
    student_affiliation: "고2",
    location: "2층 개별지도실",
    subjects: "물리2,화학2",
  },
  {
    id: 27,
    teacher: "정하람",
    hojeom: "강남점",
    date: "10/20",
    hour: "월1,2",
    proposer: "신예린",
    student_affiliation: "고3",
    location: "3층 멘토링룸",
    subjects: "국어,독서,문학",
  },
  {
    id: 28,
    teacher: "노승현",
    hojeom: "노원점",
    date: "10/21",
    hour: "화3,4",
    ropser: "김하늘",
    student_affiliation: "고1",
    location: "1층 토론실",
    subjects: "영어1,영어2",
  },
  {
    id: 29,
    teacher: "권민지",
    hojeom: "분당점",
    date: "10/22",
    hour: "수5,6",
    proposer: "박성민",
    student_affiliation: "고3",
    location: "4층 집중학습실",
    subjects: "확률과통계,기하",
  },
  {
    id: 30,
    teacher: "홍석우",
    hojeom: "일산점",
    date: "10/23",
    hour: "목1,2",
    proposer: "이채은",
    student_affiliation: "고2",
    location: "2층 상담실B",
    subjects: "생물1,생물2",
  },
  {
    id: 31,
    teacher: "안소영",
    hojeom: "송파점",
    date: "10/24",
    hour: "금3,4",
    proposer: "조민우",
    student_affiliation: "고3",
    location: "3층 개별상담실",
    subjects: "사회문화,한국사",
  },
  {
    id: 32,
    teacher: "유재현",
    hojeom: "대치점",
    date: "10/25",
    hour: "토5,6",
    proposer: "강서현",
    student_affiliation: "고1",
    location: "1층 그룹상담실",
    subjects: "통합과학,과학탐구실험",
  },
  {
    id: 33,
    teacher: "임수연",
    hojeom: "강남점",
    date: "10/26",
    hour: "일1,2",
    proposer: "문지훈",
    student_affiliation: "고3",
    location: "4층 스터디룸A",
    subjects: "물리1,물리2",
  },
  {
    id: 34,
    teacher: "장현준",
    hojeom: "노원점",
    date: "10/27",
    hour: "월5,6",
    proposer: "김예지",
    student_affiliation: "고2",
    location: "2층 질의응답실",
    subjects: "화학1,지구과학1",
  },
  {
    id: 35,
    teacher: "박시온",
    hojeom: "분당점",
    date: "10/28",
    hour: "화1,2",
    proposer: "윤도현",
    student_affiliation: "고3",
    location: "3층 개별지도실",
    subjects: "언어와매체,독서",
  },
];

export const lunchOrderTemp = [
  {
    id: 1,
    location: "송파점",
    hour: "12:00",
    name: "김민수",
    deliveryDate: "2025/9/25",
    company: "맛있는도시락",
    lunch: "불고기도시락",
    price: "8,000원",
    orderTime: "2025/9/25 10:30 AM",
  },
  {
    id: 2,
    location: "대치점",
    hour: "12:30",
    name: "박서연",
    deliveryDate: "2025/9/25",
    company: "건강한밥상",
    lunch: "제육볶음도시락",
    price: "7,500원",
    orderTime: "2025/9/25 9:15 AM",
  },
  {
    id: 3,
    location: "강남점",
    hour: "12:00",
    name: "이준호",
    deliveryDate: "2025/9/26",
    company: "도시락천국",
    lunch: "치킨마요도시락",
    price: "8,500원",
    orderTime: "2025/9/26 8:45 AM",
  },
  {
    id: 4,
    location: "노원점",
    hour: "11:30",
    name: "최지은",
    deliveryDate: "2025/9/26",
    company: "맛있는도시락",
    lunch: "비빔밥도시락",
    price: "7,000원",
    orderTime: "2025/9/26 7:20 AM",
  },
  {
    id: 5,
    location: "분당점",
    hour: "12:15",
    name: "한승우",
    deliveryDate: "2025/9/27",
    company: "프리미엄도시락",
    lunch: "갈비찜도시락",
    price: "9,500원",
    orderTime: "2025/9/27 11:10 AM",
  },
  {
    id: 6,
    location: "일산점",
    hour: "12:00",
    name: "조현우",
    deliveryDate: "2025/9/27",
    company: "건강한밥상",
    lunch: "닭갈비도시락",
    price: "8,200원",
    orderTime: "2025/9/27 2:30 PM",
  },
  {
    id: 7,
    location: "송파점",
    hour: "12:30",
    name: "신유진",
    deliveryDate: "2025/9/28",
    company: "도시락천국",
    lunch: "떡갈비도시락",
    price: "8,800원",
    orderTime: "2025/9/28 10:45 AM",
  },
  {
    id: 8,
    location: "대치점",
    hour: "12:00",
    name: "김도현",
    deliveryDate: "2025/9/28",
    company: "맛있는도시락",
    lunch: "오징어볶음도시락",
    price: "7,800원",
    orderTime: "2025/9/28 12:20 PM",
  },
  {
    id: 9,
    location: "강남점",
    hour: "11:45",
    name: "이소민",
    deliveryDate: "2025/9/29",
    company: "프리미엄도시락",
    lunch: "연어스테이크도시락",
    price: "12,000원",
    orderTime: "2025/9/29 6:50 AM",
  },
  {
    id: 10,
    location: "노원점",
    hour: "12:15",
    name: "박준영",
    deliveryDate: "2025/9/29",
    company: "건강한밥상",
    lunch: "야채비빔밥",
    price: "6,500원",
    orderTime: "2025/9/29 1:45 PM",
  },
  {
    id: 11,
    location: "분당점",
    hour: "12:00",
    name: "최민정",
    deliveryDate: "2025/9/30",
    company: "도시락천국",
    lunch: "돈까스도시락",
    price: "8,000원",
    orderTime: "2025/9/30 9:30 AM",
  },
  {
    id: 12,
    location: "일산점",
    hour: "12:30",
    name: "김나연",
    deliveryDate: "2025/9/30",
    company: "맛있는도시락",
    lunch: "김치볶음밥",
    price: "7,200원",
    orderTime: "2025/9/30 11:15 AM",
  },
  {
    id: 13,
    location: "송파점",
    hour: "12:00",
    name: "정서윤",
    deliveryDate: "2025/10/1",
    company: "프리미엄도시락",
    lunch: "한우불고기도시락",
    price: "13,500원",
    orderTime: "2025/10/1 8:20 AM",
  },
  {
    id: 14,
    location: "대치점",
    hour: "11:30",
    name: "안지호",
    deliveryDate: "2025/10/1",
    company: "건강한밥상",
    lunch: "참치마요덮밥",
    price: "6,800원",
    orderTime: "2025/10/1 10:45 AM",
  },
  {
    id: 15,
    location: "강남점",
    hour: "12:15",
    name: "홍수아",
    deliveryDate: "2025/10/2",
    company: "도시락천국",
    lunch: "새우튀김도시락",
    price: "9,200원",
    orderTime: "2025/10/2 7:50 AM",
  },
];

export const restaurantMenuTemp = [
  {
    id: 1,
    restaurantName: "맛있는도시락",
    menuName: "불고기도시락",
    price: "8,000원",
    registrant: "김관리자",
    registrationDate: "2025/9/20",
  },
  {
    id: 2,
    restaurantName: "맛있는도시락",
    menuName: "제육볶음도시락",
    price: "7,500원",
    registrant: "김관리자",
    registrationDate: "2025/9/20",
  },
  {
    id: 3,
    restaurantName: "건강한밥상",
    menuName: "비빔밥도시락",
    price: "7,000원",
    registrant: "이관리자",
    registrationDate: "2025/9/21",
  },
  {
    id: 4,
    restaurantName: "건강한밥상",
    menuName: "닭갈비도시락",
    price: "8,200원",
    registrant: "이관리자",
    registrationDate: "2025/9/21",
  },
  {
    id: 5,
    restaurantName: "도시락천국",
    menuName: "치킨마요도시락",
    price: "8,500원",
    registrant: "박관리자",
    registrationDate: "2025/9/22",
  },
  {
    id: 6,
    restaurantName: "도시락천국",
    menuName: "돈까스도시락",
    price: "8,000원",
    registrant: "박관리자",
    registrationDate: "2025/9/22",
  },
  {
    id: 7,
    restaurantName: "프리미엄도시락",
    menuName: "갈비찜도시락",
    price: "9,500원",
    registrant: "최관리자",
    registrationDate: "2025/9/23",
  },
  {
    id: 8,
    restaurantName: "프리미엄도시락",
    menuName: "연어스테이크도시락",
    price: "12,000원",
    registrant: "최관리자",
    registrationDate: "2025/9/23",
  },
  {
    id: 9,
    restaurantName: "프리미엄도시락",
    menuName: "한우불고기도시락",
    price: "13,500원",
    registrant: "최관리자",
    registrationDate: "2025/9/23",
  },
  {
    id: 10,
    restaurantName: "맛있는도시락",
    menuName: "오징어볶음도시락",
    price: "7,800원",
    registrant: "김관리자",
    registrationDate: "2025/9/24",
  },
  {
    id: 11,
    restaurantName: "건강한밥상",
    menuName: "야채비빔밥",
    price: "6,500원",
    registrant: "이관리자",
    registrationDate: "2025/9/24",
  },
  {
    id: 12,
    restaurantName: "건강한밥상",
    menuName: "참치마요덮밥",
    price: "6,800원",
    registrant: "이관리자",
    registrationDate: "2025/9/24",
  },
  {
    id: 13,
    restaurantName: "도시락천국",
    menuName: "떡갈비도시락",
    price: "8,800원",
    registrant: "박관리자",
    registrationDate: "2025/9/25",
  },
  {
    id: 14,
    restaurantName: "도시락천국",
    menuName: "새우튀김도시락",
    price: "9,200원",
    registrant: "박관리자",
    registrationDate: "2025/9/25",
  },
  {
    id: 15,
    restaurantName: "맛있는도시락",
    menuName: "김치볶음밥",
    price: "7,200원",
    registrant: "김관리자",
    registrationDate: "2025/9/25",
  },
];

export const requestStatusSecondaryTemp = [
  {
    id: 1,
    teacher: "박현주 (이화여대 약대)",
    date: "5월 18일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "영어★, 국어, 화등, ...",
  },
  {
    id: 2,
    teacher: "이선형 (카톨릭대 의대)",
    date: "5월 18일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "수1/수2/미적/화등★...",
  },
  {
    id: 3,
    teacher: "이제훈 (경희대 의대)",
    date: "5월 20일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "수1/수2/미적, 화1",
  },
  {
    id: 4,
    teacher: "이충현 (성균관대 약대)",
    date: "5월 21일",
    total_number: 4,
    number_of_applications: 3,
    application_rate: "75%",
    subjects: "[수학전문] 수1/수2/...",
  },
  {
    id: 5,
    teacher: "박현주 (이화여대 약대)",
    date: "5월 25일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "영어★, 국어, 화등, ...",
  },
  {
    id: 6,
    teacher: "김연우 (경희대 치대)",
    date: "5월 26일",
    total_number: 4,
    number_of_applications: 2,
    application_rate: "50%",
    subjects: "국어★, 수1/수2/미...",
  },
  {
    id: 7,
    teacher: "이선형 (카톨릭대 의대)",
    date: "5월 25일",
    total_number: 4,
    number_of_applications: 2,
    application_rate: "50%",
    subjects: "수1/수2/미적/화등★...",
  },
];

export const totalSubmissionsTemp = [
  {
    id: 1,
    name: "김민수",
    location: "송파점",
    date: "9/24",
    type: "외출",
    parentApproval: "승인",
    departureTime: "14:00",
    arrivalTime: "16:00",
    reason: "병원 방문",
    submissionTime: "2025/9/24 10:30 AM",
    staffApproval: "김선생",
    isApproved: "승인",
  },
  {
    id: 2,
    name: "박서연",
    location: "대치점",
    date: "9/25",
    type: "조퇴",
    parentApproval: "승인",
    departureTime: "15:30",
    arrivalTime: "-",
    reason: "가족 행사",
    submissionTime: "2025/9/25 9:15 AM",
    staffApproval: "이선생",
    isApproved: "승인",
  },
  {
    id: 3,
    name: "이준호",
    location: "강남점",
    date: "9/26",
    type: "지각",
    parentApproval: "승인",
    departureTime: "-",
    arrivalTime: "10:30",
    reason: "교통 체증",
    submissionTime: "2025/9/26 8:45 AM",
    staffApproval: "박선생",
    isApproved: "대기",
  },
  {
    id: 4,
    name: "최지은",
    location: "노원점",
    date: "9/27",
    type: "결석",
    parentApproval: "승인",
    departureTime: "-",
    arrivalTime: "-",
    reason: "몸살감기",
    submissionTime: "2025/9/27 7:20 AM",
    staffApproval: "정선생",
    isApproved: "승인",
  },
  {
    id: 5,
    name: "한승우",
    location: "분당점",
    date: "9/28",
    type: "외출",
    parentApproval: "대기",
    departureTime: "13:00",
    arrivalTime: "15:00",
    reason: "학원 상담",
    submissionTime: "2025/9/28 11:10 AM",
    staffApproval: "김선생",
    isApproved: "대기",
  },
  {
    id: 6,
    name: "조현우",
    location: "일산점",
    date: "9/29",
    type: "조퇴",
    parentApproval: "승인",
    departureTime: "16:00",
    arrivalTime: "-",
    reason: "치과 치료",
    submissionTime: "2025/9/29 2:30 PM",
    staffApproval: "윤선생",
    isApproved: "승인",
  },
  {
    id: 7,
    name: "신유진",
    location: "송파점",
    date: "9/30",
    type: "지각",
    parentApproval: "승인",
    departureTime: "-",
    arrivalTime: "11:15",
    reason: "늦잠",
    submissionTime: "2025/9/30 10:45 AM",
    staffApproval: "강선생",
    isApproved: "거부",
  },
  {
    id: 8,
    name: "김도현",
    location: "대치점",
    date: "10/1",
    type: "외출",
    parentApproval: "승인",
    departureTime: "14:30",
    arrivalTime: "17:00",
    reason: "대학 입시 상담",
    submissionTime: "2025/10/1 12:20 PM",
    staffApproval: "장선생",
    isApproved: "승인",
  },
  {
    id: 9,
    name: "이소민",
    location: "강남점",
    date: "10/2",
    type: "결석",
    parentApproval: "승인",
    departureTime: "-",
    arrivalTime: "-",
    reason: "독감",
    submissionTime: "2025/10/2 6:50 AM",
    staffApproval: "임선생",
    isApproved: "승인",
  },
  {
    id: 10,
    name: "박준영",
    location: "노원점",
    date: "10/3",
    type: "조퇴",
    parentApproval: "대기",
    departureTime: "15:00",
    arrivalTime: "-",
    reason: "동생 학부모 상담",
    submissionTime: "2025/10/3 1:45 PM",
    staffApproval: "오선생",
    isApproved: "대기",
  },
];

export const depositHistoryTemp = [
  {
    id: 1,
    depositorName: "김민수",
    depositAmount: "50,000원",
    depositTime: "2025/9/23 14:30",
    sellerInfo: "매점됨",
    seller: "박서연",
    sellTime: "2025/9/24 10:15",
    recipient: "이관리자",
  },
  {
    id: 2,
    depositorName: "이준호",
    depositAmount: "30,000원",
    depositTime: "2025/9/24 09:45",
    sellerInfo: "매점됨",
    seller: "최지은",
    sellTime: "2025/9/24 16:20",
    recipient: "김관리자",
  },
  {
    id: 3,
    depositorName: "박서연",
    depositAmount: "20,000원",
    depositTime: "2025/9/24 11:20",
    sellerInfo: "매점 안됨",
    seller: "-",
    sellTime: "-",
    recipient: "-",
  },
  {
    id: 4,
    depositorName: "최지은",
    depositAmount: "40,000원",
    depositTime: "2025/9/25 08:30",
    sellerInfo: "매점됨",
    seller: "한승우",
    sellTime: "2025/9/25 14:45",
    recipient: "박관리자",
  },
  {
    id: 5,
    depositorName: "한승우",
    depositAmount: "25,000원",
    depositTime: "2025/9/25 13:15",
    sellerInfo: "매점 안됨",
    seller: "-",
    sellTime: "-",
    recipient: "-",
  },
  {
    id: 6,
    depositorName: "조현우",
    depositAmount: "35,000원",
    depositTime: "2025/9/26 10:00",
    sellerInfo: "매점됨",
    seller: "신유진",
    sellTime: "2025/9/26 15:30",
    recipient: "정관리자",
  },
  {
    id: 7,
    depositorName: "신유진",
    depositAmount: "15,000원",
    depositTime: "2025/9/26 16:45",
    sellerInfo: "매점 안됨",
    seller: "-",
    sellTime: "-",
    recipient: "-",
  },
  {
    id: 8,
    depositorName: "김도현",
    depositAmount: "60,000원",
    depositTime: "2025/9/27 09:20",
    sellerInfo: "매점됨",
    seller: "이소민",
    sellTime: "2025/9/27 13:10",
    recipient: "최관리자",
  },
  {
    id: 9,
    depositorName: "이소민",
    depositAmount: "45,000원",
    depositTime: "2025/9/27 14:50",
    sellerInfo: "매점됨",
    seller: "박준영",
    sellTime: "2025/9/28 11:25",
    recipient: "김관리자",
  },
  {
    id: 10,
    depositorName: "박준영",
    depositAmount: "28,000원",
    depositTime: "2025/9/28 12:35",
    sellerInfo: "매점 안됨",
    seller: "-",
    sellTime: "-",
    recipient: "-",
  },
  {
    id: 11,
    depositorName: "정서윤",
    depositAmount: "55,000원",
    depositTime: "2025/9/29 07:40",
    sellerInfo: "매점됨",
    seller: "안지호",
    sellTime: "2025/9/29 16:15",
    recipient: "이관리자",
  },
  {
    id: 12,
    depositorName: "안지호",
    depositAmount: "32,000원",
    depositTime: "2025/9/29 11:10",
    sellerInfo: "매점 안됨",
    seller: "-",
    sellTime: "-",
    recipient: "-",
  },
  {
    id: 13,
    depositorName: "홍수아",
    depositAmount: "42,000원",
    depositTime: "2025/9/30 08:55",
    sellerInfo: "매점됨",
    seller: "강민석",
    sellTime: "2025/9/30 14:30",
    recipient: "박관리자",
  },
  {
    id: 14,
    depositorName: "강민석",
    depositAmount: "18,000원",
    depositTime: "2025/9/30 15:20",
    sellerInfo: "매점 안됨",
    seller: "-",
    sellTime: "-",
    recipient: "-",
  },
  {
    id: 15,
    depositorName: "윤채원",
    depositAmount: "38,000원",
    depositTime: "2025/10/1 10:25",
    sellerInfo: "매점됨",
    seller: "서준호",
    sellTime: "2025/10/1 17:45",
    recipient: "정관리자",
  },
];

export const chargeApplicationTemp = [
  {
    id: 1,
    branch: "송파점",
    applicationId: "student123",
    applicantName: "김민수",
    applicationAmount: "50,000원",
    applicationTime: "2025/9/23 14:30",
    matchStatus: "매칭됨",
    matchTime: "2025/9/23 14:35",
  },
  {
    id: 2,
    branch: "대치점",
    applicationId: "user456",
    applicantName: "이준호",
    applicationAmount: "30,000원",
    applicationTime: "2025/9/24 09:45",
    matchStatus: "매칭됨",
    matchTime: "2025/9/24 09:50",
  },
  {
    id: 3,
    branch: "강남점",
    applicationId: "apply789",
    applicantName: "박서연",
    applicationAmount: "20,000원",
    applicationTime: "2025/9/24 11:20",
    matchStatus: "비매칭",
    matchTime: "-",
  },
  {
    id: 4,
    branch: "노원점",
    applicationId: "charge001",
    applicantName: "최지은",
    applicationAmount: "40,000원",
    applicationTime: "2025/9/25 08:30",
    matchStatus: "매칭됨",
    matchTime: "2025/9/25 08:45",
  },
  {
    id: 5,
    branch: "분당점",
    applicationId: "request202",
    applicantName: "한승우",
    applicationAmount: "25,000원",
    applicationTime: "2025/9/25 13:15",
    matchStatus: "비매칭",
    matchTime: "-",
  },
  {
    id: 6,
    branch: "일산점",
    applicationId: "pay333",
    applicantName: "조현우",
    applicationAmount: "35,000원",
    applicationTime: "2025/9/26 10:00",
    matchStatus: "매칭됨",
    matchTime: "2025/9/26 15:30",
  },
  {
    id: 7,
    branch: "송파점",
    applicationId: "load444",
    applicantName: "신유진",
    applicationAmount: "15,000원",
    applicationTime: "2025/9/26 16:45",
    matchStatus: "비매칭",
    matchTime: "-",
  },
  {
    id: 8,
    branch: "대치점",
    applicationId: "money555",
    applicantName: "김도현",
    applicationAmount: "60,000원",
    applicationTime: "2025/9/27 09:20",
    matchStatus: "매칭됨",
    matchTime: "2025/9/27 13:10",
  },
  {
    id: 9,
    branch: "강남점",
    applicationId: "cash666",
    applicantName: "이소민",
    applicationAmount: "45,000원",
    applicationTime: "2025/9/27 14:50",
    matchStatus: "매칭됨",
    matchTime: "2025/9/28 11:25",
  },
  {
    id: 10,
    branch: "노원점",
    applicationId: "fund777",
    applicantName: "박준영",
    applicationAmount: "28,000원",
    applicationTime: "2025/9/28 12:35",
    matchStatus: "비매칭",
    matchTime: "-",
  },
  {
    id: 11,
    branch: "분당점",
    applicationId: "balance888",
    applicantName: "정서윤",
    applicationAmount: "55,000원",
    applicationTime: "2025/9/29 07:40",
    matchStatus: "매칭됨",
    matchTime: "2025/9/29 16:15",
  },
  {
    id: 12,
    branch: "일산점",
    applicationId: "credit999",
    applicantName: "안지호",
    applicationAmount: "32,000원",
    applicationTime: "2025/9/29 11:10",
    matchStatus: "비매칭",
    matchTime: "-",
  },
  {
    id: 13,
    branch: "송파점",
    applicationId: "top100",
    applicantName: "홍수아",
    applicationAmount: "42,000원",
    applicationTime: "2025/9/30 08:55",
    matchStatus: "매칭됨",
    matchTime: "2025/9/30 14:30",
  },
  {
    id: 14,
    branch: "대치점",
    applicationId: "fill200",
    applicantName: "강민석",
    applicationAmount: "18,000원",
    applicationTime: "2025/9/30 15:20",
    matchStatus: "비매칭",
    matchTime: "-",
  },
  {
    id: 15,
    branch: "강남점",
    applicationId: "load300",
    applicantName: "윤채원",
    applicationAmount: "38,000원",
    applicationTime: "2025/10/1 10:25",
    matchStatus: "매칭됨",
    matchTime: "2025/10/1 17:45",
  },
];

export const refundTemp = [
  {
    id: 1,
    name: "김민수",
    refundAmount: "50,000원",
    refundDate: "2025/9/23",
    person: "이관리자",
  },
  {
    id: 2,
    name: "이준호",
    refundAmount: "30,000원",
    refundDate: "2025/9/24",
    person: "김관리자",
  },
  {
    id: 3,
    name: "박서연",
    refundAmount: "20,000원",
    refundDate: "2025/9/24",
    person: "박관리자",
  },
  {
    id: 4,
    name: "최지은",
    refundAmount: "40,000원",
    refundDate: "2025/9/25",
    person: "정관리자",
  },
  {
    id: 5,
    name: "한승우",
    refundAmount: "25,000원",
    refundDate: "2025/9/25",
    person: "최관리자",
  },
  {
    id: 6,
    name: "조현우",
    refundAmount: "35,000원",
    refundDate: "2025/9/26",
    person: "이관리자",
  },
  {
    id: 7,
    name: "신유진",
    refundAmount: "15,000원",
    refundDate: "2025/9/26",
    person: "김관리자",
  },
  {
    id: 8,
    name: "김도현",
    refundAmount: "60,000원",
    refundDate: "2025/9/27",
    person: "박관리자",
  },
  {
    id: 9,
    name: "이소민",
    refundAmount: "45,000원",
    refundDate: "2025/9/27",
    person: "정관리자",
  },
  {
    id: 10,
    name: "박준영",
    refundAmount: "28,000원",
    refundDate: "2025/9/28",
    person: "최관리자",
  },
  {
    id: 11,
    name: "정서윤",
    refundAmount: "55,000원",
    refundDate: "2025/9/29",
    person: "이관리자",
  },
  {
    id: 12,
    name: "안지호",
    refundAmount: "32,000원",
    refundDate: "2025/9/29",
    person: "김관리자",
  },
  {
    id: 13,
    name: "홍수아",
    refundAmount: "42,000원",
    refundDate: "2025/9/30",
    person: "박관리자",
  },
  {
    id: 14,
    name: "강민석",
    refundAmount: "18,000원",
    refundDate: "2025/9/30",
    person: "정관리자",
  },
  {
    id: 15,
    name: "윤채원",
    refundAmount: "38,000원",
    refundDate: "2025/10/1",
    person: "최관리자",
  },
];

export const messageTemp = [
  {
    id: "1",
    senderName: "백선영",
    senderRole: "강남점",
    message: "2022학주시면 될 것 같아요",
    timestamp: "오전 10:55(+3분)",
    unreadCount: 1,
  },
  {
    id: "2",
    senderName: "김민수",
    senderRole: "송파점",
    message: "오늘 수업 자료 확인 부탁드립니다",
    timestamp: "오전 9:30(+15분)",
    unreadCount: 2,
  },
  {
    id: "3",
    senderName: "이동민",
    senderRole: "대치점",
    message: "학생 상담 일정을 조율해야 할 것 같습니다",
    timestamp: "오전 8:45(+1시간)",
    unreadCount: 0,
  },
  {
    id: "4",
    senderName: "박서연",
    senderRole: "노원점",
    message: "내일 회의 준비 사항 공유드립니다",
    timestamp: "어제 17:20",
    unreadCount: 3,
  },
  {
    id: "5",
    senderName: "최지은",
    senderRole: "분당점",
    message: "시험 일정 변경에 대한 공지사항입니다",
    timestamp: "어제 15:10",
    unreadCount: 0,
  },
  {
    id: "6",
    senderName: "한승우",
    senderRole: "일산점",
    message: "학부모 상담 피드백 전달드립니다",
    timestamp: "어제 14:35",
    unreadCount: 1,
  },
  {
    id: "7",
    senderName: "조현우",
    senderRole: "강남점",
    message: "새로운 교재 도입 건에 대해 논의하고 싶습니다",
    timestamp: "9/24 16:25",
    unreadCount: 0,
  },
  {
    id: "8",
    senderName: "신유진",
    senderRole: "송파점",
    message: "학생 출석률 개선 방안을 공유드립니다",
    timestamp: "9/24 13:40",
    unreadCount: 2,
  },
  {
    id: "9",
    senderName: "김도현",
    senderRole: "대치점",
    message: "이번 달 성과 보고서 제출했습니다",
    timestamp: "9/23 18:20",
    unreadCount: 0,
  },
  {
    id: "10",
    senderName: "이소민",
    senderRole: "노원점",
    message: "특강 일정 확정되었습니다. 확인 부탁드려요",
    timestamp: "9/23 11:15",
    unreadCount: 1,
  },
  {
    id: "11",
    senderName: "이소민",
    senderRole: "노원점",
    message: "특강 일정 확정되었습니다. 확인 부탁드려요",
    timestamp: "9/23 11:15",
    unreadCount: 1,
  },
  {
    id: "12",
    senderName: "이소민",
    senderRole: "노원점",
    message: "특강 일정 확정되었습니다. 확인 부탁드려요",
    timestamp: "9/23 11:15",
    unreadCount: 1,
  },
  {
    id: "13",
    senderName: "이소민",
    senderRole: "노원점",
    message: "특강 일정 확정되었습니다. 확인 부탁드려요",
    timestamp: "9/23 11:15",
    unreadCount: 1,
  },
  {
    id: "14",
    senderName: "이소민",
    senderRole: "노원점",
    message: "특강 일정 확정되었습니다. 확인 부탁드려요",
    timestamp: "9/23 11:15",
    unreadCount: 1,
  },
  {
    id: "15",
    senderName: "이소민",
    senderRole: "노원점",
    message: "특강 일정 확정되었습니다. 확인 부탁드려요",
    timestamp: "9/23 11:15",
    unreadCount: 1,
  },
];

export const unresolvedMessageTemp = [
  {
    id: "1",
    senderName: "김지훈",
    senderLocation: "강남점",
    message:
      "급식 신청 관련 문의드립니다. 다음 주 메뉴 변경 가능한지 확인 부탁드려요.",
  },
  {
    id: "2",
    senderName: "이수진",
    senderLocation: "송파점",
    message:
      "학습 진도 체크 일정 조정이 필요합니다. 면담 시간 재조정 가능할까요?",
  },
  {
    id: "3",
    senderName: "박현우",
    senderLocation: "대치점",
    message:
      "벌점 관련 이의제기 건으로 연락드렸습니다. 검토 후 회신 부탁드립니다.",
  },
];

export const allMessagesTemp = [
  {
    id: "1",
    chatroomId: "CR001",
    sender: "김민수",
    time: "2025-09-26 09:30:15",
    from: "강남점",
    to: "송파점",
    content: "오늘 수업 자료 공유 부탁드립니다.",
    readStatus: "읽음",
  },
  {
    id: "2",
    chatroomId: "CR002",
    sender: "이지은",
    time: "2025-09-26 09:25:42",
    from: "대치점",
    to: "노원점",
    content: "학생 상담 일정 조율이 필요합니다.",
    readStatus: "읽지 않음",
  },
  {
    id: "3",
    chatroomId: "CR003",
    sender: "박상호",
    time: "2025-09-26 09:20:18",
    from: "분당점",
    to: "일산점",
    content: "급식 신청서 확인 부탁드립니다.",
    readStatus: "읽음",
  },
  {
    id: "4",
    chatroomId: "CR004",
    sender: "최수연",
    time: "2025-09-26 09:15:33",
    from: "강남점",
    to: "대치점",
    content: "벌점 관련 문의사항이 있습니다.",
    readStatus: "읽지 않음",
  },
  {
    id: "5",
    chatroomId: "CR005",
    sender: "정민우",
    time: "2025-09-26 09:10:27",
    from: "송파점",
    to: "분당점",
    content: "시험 일정 변경 공지드립니다.",
    readStatus: "읽음",
  },
  {
    id: "6",
    chatroomId: "CR006",
    sender: "한서영",
    time: "2025-09-26 09:05:14",
    from: "노원점",
    to: "강남점",
    content: "학부모 상담 피드백 전달드립니다.",
    readStatus: "읽지 않음",
  },
  {
    id: "7",
    chatroomId: "CR007",
    sender: "윤태현",
    time: "2025-09-26 09:00:56",
    from: "일산점",
    to: "송파점",
    content: "특강 일정 확정되었습니다.",
    readStatus: "읽음",
  },
  {
    id: "8",
    chatroomId: "CR008",
    sender: "류희정",
    time: "2025-09-26 08:55:41",
    from: "대치점",
    to: "일산점",
    content: "교재 주문 관련 안내드립니다.",
    readStatus: "읽지 않음",
  },
  {
    id: "9",
    chatroomId: "CR009",
    sender: "강동욱",
    time: "2025-09-26 08:50:22",
    from: "분당점",
    to: "노원점",
    content: "출석체크 시스템 오류 보고드립니다.",
    readStatus: "읽음",
  },
  {
    id: "10",
    chatroomId: "CR010",
    sender: "오연서",
    time: "2025-09-26 08:45:03",
    from: "강남점",
    to: "대치점",
    content: "월말 정산 자료 전송완료했습니다.",
    readStatus: "읽지 않음",
  },
];

export const groupSendTemp = [
  {
    id: "1",
    branch: "강남점",
    studentNumber: "A-001",
    name: "김민수",
    selection: "학생",
  },
  {
    id: "2",
    branch: "강남점",
    studentNumber: "A-002",
    name: "이지은",
    selection: "학부모",
  },
  {
    id: "3",
    branch: "대치점",
    studentNumber: "B-001",
    name: "박상호",
    selection: "학생",
  },
  {
    id: "4",
    branch: "대치점",
    studentNumber: "B-002",
    name: "최수연",
    selection: "학부모",
  },
  {
    id: "5",
    branch: "송파점",
    studentNumber: "C-001",
    name: "정민우",
    selection: "학생",
  },
  {
    id: "6",
    branch: "송파점",
    studentNumber: "C-002",
    name: "한서영",
    selection: "학부모",
  },
  {
    id: "7",
    branch: "대치3층",
    studentNumber: "D-001",
    name: "윤태현",
    selection: "학생",
  },
  {
    id: "8",
    branch: "대치6층",
    studentNumber: "E-001",
    name: "류희정",
    selection: "학부모",
  },
  {
    id: "9",
    branch: "강남2호점",
    studentNumber: "F-001",
    name: "강동욱",
    selection: "학생",
  },
  {
    id: "10",
    branch: "대구점",
    studentNumber: "G-001",
    name: "오연서",
    selection: "학부모",
  },
];

export const callTextMessageTemp = [
  {
    id: "1",
    direction: "수신",
    type: "전화",
    oppositeParty: "김학부모",
    responsiblePerson: "이선생님",
    content: "자녀 성적 상담 요청드립니다",
    callTime: "00:03:45",
    responseTime: "00:00:15",
    sender: "강남점",
  },
  {
    id: "2", 
    direction: "발신",
    type: "문자",
    oppositeParty: "박학부모",
    responsiblePerson: "김선생님",
    content: "내일 수업 일정 변경 안내드립니다",
    callTime: "-",
    responseTime: "즉시",
    sender: "대치점",
  },
  {
    id: "3",
    direction: "수신",
    type: "전화",
    oppositeParty: "최학부모",
    responsiblePerson: "정선생님",
    content: "급식 신청 관련 문의",
    callTime: "00:02:20",
    responseTime: "00:01:30",
    sender: "송파점",
  },
  {
    id: "4",
    direction: "발신",
    type: "문자",
    oppositeParty: "윤학부모",
    responsiblePerson: "한선생님", 
    content: "시험 결과 안내 및 상담 일정 조율",
    callTime: "-",
    responseTime: "즉시",
    sender: "대치3층",
  },
  {
    id: "5",
    direction: "수신",
    type: "전화",
    oppositeParty: "류학부모",
    responsiblePerson: "오선생님",
    content: "학습 진도 상담 요청",
    callTime: "00:05:12",
    responseTime: "00:00:45",
    sender: "대치6층",
  },
  {
    id: "6",
    direction: "발신",
    type: "문자",
    oppositeParty: "강학부모",
    responsiblePerson: "백선생님",
    content: "벌점 처리 결과 안내",
    callTime: "-",
    responseTime: "즉시",
    sender: "강남2호점",
  },
  {
    id: "7",
    direction: "수신",
    type: "전화",
    oppositeParty: "남학부모",
    responsiblePerson: "송선생님",
    content: "출석 관련 문의사항",
    callTime: "00:01:55",
    responseTime: "00:00:30",
    sender: "대구점",
  },
  {
    id: "8",
    direction: "발신",
    type: "문자",
    oppositeParty: "서학부모",
    responsiblePerson: "안선생님",
    content: "특강 신청 마감 안내",
    callTime: "-",
    responseTime: "즉시",
    sender: "강남점",
  },
];

export const suggestionTemp = [
  {
    id: "1",
    applicant: "김민수",
    type: "생활",
    content: "에어컨 온도 조절 요청드립니다",
    submissionDate: "2025-09-25",
    processingStatus: "처리중",
    confirmationNumber: "SGT001",
    completionDate: "-",
    outcome: "1일",
  },
  {
    id: "2",
    applicant: "익명",
    type: "자리변경",
    content: "소음이 심한 자리에서 다른 곳으로 이동하고 싶습니다",
    submissionDate: "2025-09-24",
    processingStatus: "완료",
    confirmationNumber: "SGT002",
    completionDate: "2025-09-25",
    outcome: "2일",
  },
  {
    id: "3",
    applicant: "박지은",
    type: "담임상담",
    content: "학습 진도 관련 개별 상담 신청",
    submissionDate: "2025-09-23",
    processingStatus: "대기중",
    confirmationNumber: "SGT003",
    completionDate: "-",
    outcome: "3일",
  },
  {
    id: "4",
    applicant: "이수진",
    type: "기타",
    content: "급식 메뉴 개선 건의사항",
    submissionDate: "2025-09-22",
    processingStatus: "완료",
    confirmationNumber: "SGT004",
    completionDate: "2025-09-24",
    outcome: "4일",
  },
  {
    id: "5",
    applicant: "익명",
    type: "담임평가",
    content: "강사님 수업 방식에 대한 건의",
    submissionDate: "2025-09-21",
    processingStatus: "처리중",
    confirmationNumber: "SGT005",
    completionDate: "-",
    outcome: "5일",
  },
  {
    id: "6",
    applicant: "최민호",
    type: "생활평가",
    content: "휴게 공간 확충 요청",
    submissionDate: "2025-09-20",
    processingStatus: "완료",
    confirmationNumber: "SGT006",
    completionDate: "2025-09-22",
    outcome: "6일",
  },
  {
    id: "7",
    applicant: "한서연",
    type: "집의응답",
    content: "부모님께 전달사항 있습니다",
    submissionDate: "2025-09-19",
    processingStatus: "대기중",
    confirmationNumber: "SGT007",
    completionDate: "-",
    outcome: "7일",
  },
  {
    id: "8",
    applicant: "익명",
    type: "대표에게만",
    content: "개인적인 건의사항입니다",
    submissionDate: "2025-09-18",
    processingStatus: "처리중",
    confirmationNumber: "SGT008",
    completionDate: "-",
    outcome: "8일",
  },
];

export const mySuggestionTemp = [
  {
    id: "1",
    type: "생활",
    applicant: "김민수",
    number: "강남점",
    content: "에어컨 온도 조절 요청드립니다",
    submissionDate: "2025-09-25",
    processingStatus: "처리중",
  },
  {
    id: "2",
    type: "자리변경",
    applicant: "김민수", 
    number: "강남점",
    content: "창가 자리로 이동 요청합니다",
    submissionDate: "2025-09-24",
    processingStatus: "완료",
  },
  {
    id: "3",
    type: "담임상담",
    applicant: "김민수",
    number: "강남점",
    content: "학습 진도 상담 신청드립니다",
    submissionDate: "2025-09-23",
    processingStatus: "대기중",
  },
  {
    id: "4",
    type: "기타",
    applicant: "김민수",
    number: "강남점",
    content: "급식 메뉴 개선 건의사항",
    submissionDate: "2025-09-22",
    processingStatus: "완료",
  },
  {
    id: "5",
    type: "생활평가",
    applicant: "김민수",
    number: "강남점",
    content: "휴게 공간 확충 요청",
    submissionDate: "2025-09-21",
    processingStatus: "처리중",
  },
];

export const allSuggestionTemp = [
  {
    id: "1",
    type: "생활",
    applicant: "김민수",
    number: "강남점",
    content: "에어컨 온도 조절 요청드립니다",
    submissionDate: "2025-09-25",
    processingStatus: "처리중",
    confirmationNumber: "SGT001",
    completionDate: "-",
    outcome: "1일",
    deletionDate: "첨부",
    deletionDate2: "첨부",
  },
  {
    id: "2",
    type: "자리변경",
    applicant: "익명",
    number: "대치점",
    content: "소음이 심한 자리에서 다른 곳으로 이동하고 싶습니다",
    submissionDate: "2025-09-24",
    processingStatus: "완료",
    confirmationNumber: "SGT002",
    completionDate: "2025-09-25",
    outcome: "2일",
    deletionDate: "-",
    deletionDate2: "-",
  },
  {
    id: "3",
    type: "담임상담",
    applicant: "박지은",
    number: "송파점",
    content: "학습 진도 관련 개별 상담 신청",
    submissionDate: "2025-09-23",
    processingStatus: "대기중",
    confirmationNumber: "SGT003",
    completionDate: "-",
    outcome: "3일",
    deletionDate: "첨부",
    deletionDate2: "-",
  },
  {
    id: "4",
    type: "기타",
    applicant: "이수진",
    number: "대치3층",
    content: "급식 메뉴 개선 건의사항",
    submissionDate: "2025-09-22",
    processingStatus: "완료",
    confirmationNumber: "SGT004",
    completionDate: "2025-09-24",
    outcome: "4일",
    deletionDate: "-",
    deletionDate2: "첨부",
  },
  {
    id: "5",
    type: "담임평가",
    applicant: "익명",
    number: "대치6층",
    content: "강사님 수업 방식에 대한 건의",
    submissionDate: "2025-09-21",
    processingStatus: "처리중",
    confirmationNumber: "SGT005",
    completionDate: "-",
    outcome: "5일",
    deletionDate: "첨부",
    deletionDate2: "첨부",
  },
  {
    id: "6",
    type: "생활평가",
    applicant: "최민호",
    number: "강남2호점",
    content: "휴게 공간 확충 요청",
    submissionDate: "2025-09-20",
    processingStatus: "완료",
    confirmationNumber: "SGT006",
    completionDate: "2025-09-22",
    outcome: "6일",
    deletionDate: "-",
    deletionDate2: "-",
  },
  {
    id: "7",
    type: "집의응답",
    applicant: "한서연",
    number: "대구점",
    content: "부모님께 전달사항 있습니다",
    submissionDate: "2025-09-19",
    processingStatus: "대기중",
    confirmationNumber: "SGT007",
    completionDate: "-",
    outcome: "7일",
    deletionDate: "첨부",
    deletionDate2: "-",
  },
  {
    id: "8",
    type: "대표에게만",
    applicant: "익명",
    number: "강남점",
    content: "개인적인 건의사항입니다",
    submissionDate: "2025-09-18",
    processingStatus: "처리중",
    confirmationNumber: "SGT008",
    completionDate: "-",
    outcome: "8일",
    deletionDate: "-",
    deletionDate2: "첨부",
  },
];
