export const noticeTemp = [
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    title: "10월 연휴 원내 이용 공지",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.23",
  },
  {
    image: "/images/temp/notice_card_image_1.jpeg",
    title: "9/22-9/27 정기식 식단",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
  {
    image: "/images/temp/notice_card_image_2.jpeg",
    title: "9/19 (금) 대성 더프리미엄 모의고사 빠른정답 및",
    description:
      "📌 운영 안내 (시설이용은 연중무휴 06:00~24:00 운영) @ 출석체크 및 벌점 - 10/6(월)·10/7(화): 자율등원, 출석체크·벌점",
    date: "2025.9.19",
  },
];

export const qnaRequestsTemp = [
  {
    date: "9월 24일 수요일",
    timeSlots: "수1,2,학등★,사문★, 점법",
    name: "채희준",
    description: "(고려대 경영학과)",
    additionalInfo: "원족상담실 (#암순서부터 신청 #문제해설 진술) - 송파점",
    year: 2025,
    month: 10,
    selectedDate: new Date(2025, 9, 15),
  },
  {
    date: "9월 24일 수요일",
    timeSlots: "수1,2,미적★,물1★,생1",
    name: "이동민",
    description: "(한양대 의대)",
    additionalInfo:
      "2층 오른쪽상담실(#암순서부터 신청 #문제해설 진술) - 대치점 전체",
    year: 2025,
    month: 11,
    selectedDate: new Date(2025, 10, 7),
  },
];

export const postsTemp = [
  {
    username: "gy2551",
    timestamp: "2025/9/25 9:7 AM",
    title: "손가락 걸기 1번선지?",
    content: "키모4회인데 1번도 맞다고 볼 수 있지 않나요? 어떻게 생각하시나요?",
    imageSrc: "/images/temp/notice_card_image_1.jpeg",
    avatarSrc: undefined,
    likesCount: 1,
    comments: [
      {
        username: "조예민",
        userTitle: "고려대 행정학과",
        content:
          "<보기>에 주어진 예시에서 '므'의 'ㅇ', '드'의 'ㄱ', '느'의 'ㅗ'로 잘못 발음될 것을 참고해 선처에 적용시켜주시면 됩니다.",
        timestamp: "2025/9/24 3:33 PM",
        avatarSrc: undefined,
      },
    ],
  },
  {
    username: "pvulleur",
    timestamp: "2025/9/23 4:45 PM",
    title: "언매",
    content: "잘못 받을 될 수 있는걸 제가 어떻게 판단해야하는건가요..?",
    imageSrc: "/images/temp/notice_card_image_2.jpeg",
    avatarSrc: undefined,
    likesCount: 0,
    comments: [],
  },
  {
    username: "student123",
    timestamp: "2025/9/22 2:15 PM",
    title: "수학 미적분 문제 질문",
    content:
      "이 문제 풀이 과정에서 막혔습니다. 도함수 구하는 부분에서 실수가 있는 것 같은데 확인 부탁드려요.",
    imageSrc: "/images/temp/notice_card_image_1.jpeg",
    avatarSrc: undefined,
    likesCount: 3,
    comments: [
      {
        username: "김선생",
        userTitle: "서울대 수학과",
        content:
          "이 부분에서 연쇄법칙을 적용할 때 내부함수의 미분을 빼먹으신 것 같습니다. (x²+1)을 미분하면 2x가 나와야 합니다.",
        timestamp: "2025/9/22 3:20 PM",
        avatarSrc: undefined,
      },
      {
        username: "mathhelper",
        userTitle: "연세대 응용수학과",
        content:
          "김선생님 말씀이 맞습니다. 그리고 추가로 상수항 처리도 조심하세요. 단계별로 천천히 계산해보시면 됩니다.",
        timestamp: "2025/9/22 4:10 PM",
        avatarSrc: undefined,
      },
    ],
  },
];

export const requestStatusTemp = [
  {
    id: 1,
    teacher: "채희준",
    hojeom: "송파점",
    date: "9/24",
    hour: "수1,2",
    proposer: "김민수",
    student_affiliation: "고3",
    location: "원족상담실",
    subjects: "수1,2,학등★,사문★, 점법",
  },
  {
    id: 2,
    teacher: "이동민",
    hojeom: "대치점",
    date: "9/25",
    hour: "수3,4",
    proposer: "박서연",
    student_affiliation: "고2",
    location: "2층 오른쪽상담실",
    subjects: "수1,2,미적★,물1★,생1",
  },
  {
    id: 3,
    teacher: "정수한",
    hojeom: "강남점",
    date: "9/26",
    hour: "화5,6",
    proposer: "이준호",
    student_affiliation: "고3",
    location: "3층 상담실A",
    subjects: "화학1,화학2,생물1",
  },
  {
    id: 4,
    teacher: "김영희",
    hojeom: "노원점",
    date: "9/27",
    hour: "목1,2",
    proposer: "최지은",
    student_affiliation: "고1",
    location: "1층 개별상담실",
    subjects: "국어,문학,화작",
  },
  {
    id: 5,
    teacher: "박철수",
    hojeom: "분당점",
    date: "9/28",
    hour: "금3,4",
    proposer: "한승우",
    student_affiliation: "고3",
    location: "4층 그룹스터디실",
    subjects: "영어,영독,영작",
  },
  {
    id: 6,
    teacher: "윤미나",
    hojeom: "일산점",
    date: "9/29",
    hour: "월1,2",
    proposer: "조현우",
    student_affiliation: "고2",
    location: "2층 멘토링실",
    subjects: "수학1,수학2,확통",
  },
  {
    id: 7,
    teacher: "강태훈",
    hojeom: "송파점",
    date: "9/30",
    hour: "화3,4",
    proposer: "신유진",
    student_affiliation: "고3",
    location: "3층 개별지도실",
    subjects: "물리1,물리2",
  },
  {
    id: 8,
    teacher: "장서현",
    hojeom: "대치점",
    date: "10/1",
    hour: "수5,6",
    proposer: "김도현",
    student_affiliation: "고1",
    location: "1층 그룹상담실",
    subjects: "생물1,지구과학1",
  },
  {
    id: 9,
    teacher: "임현수",
    hojeom: "강남점",
    date: "10/2",
    hour: "목1,2",
    proposer: "이소민",
    student_affiliation: "고3",
    location: "4층 스터디룸A",
    subjects: "화학1,화학2",
  },
  {
    id: 10,
    teacher: "오지훈",
    hojeom: "노원점",
    date: "10/3",
    hour: "금5,6",
    proposer: "박준영",
    student_affiliation: "고2",
    location: "2층 토론실",
    subjects: "한국사,세계사",
  },
  {
    id: 11,
    teacher: "한예슬",
    hojeom: "분당점",
    date: "10/4",
    hour: "토1,2",
    proposer: "최민정",
    student_affiliation: "고3",
    location: "3층 집중학습실",
    subjects: "미적분,기하",
  },
  {
    id: 12,
    teacher: "서동현",
    hojeom: "일산점",
    date: "10/5",
    hour: "일3,4",
    proposer: "김나연",
    student_affiliation: "고1",
    location: "1층 상담실B",
    subjects: "영어1,영어회화",
  },
  {
    id: 13,
    teacher: "류정호",
    hojeom: "송파점",
    date: "10/6",
    hour: "월5,6",
    proposer: "정서윤",
    student_affiliation: "고3",
    location: "4층 질의응답실",
    subjects: "국어,문학",
  },
  {
    id: 14,
    teacher: "민경아",
    hojeom: "대치점",
    date: "10/7",
    hour: "화1,2",
    proposer: "안지호",
    student_affiliation: "고2",
    location: "2층 개별상담실",
    subjects: "사회문화,정치와법",
  },
  {
    id: 15,
    teacher: "신재민",
    hojeom: "강남점",
    date: "10/8",
    hour: "수3,4",
    proposer: "홍수아",
    student_affiliation: "고3",
    location: "3층 멘토링룸",
    subjects: "경제,사회문화",
  },
  {
    id: 16,
    teacher: "배수진",
    hojeom: "노원점",
    date: "10/9",
    hour: "목5,6",
    proposer: "강민석",
    student_affiliation: "고1",
    location: "1층 그룹스터디실",
    subjects: "통합과학,통합사회",
  },
  {
    id: 17,
    teacher: "김다은",
    hojeom: "분당점",
    date: "10/10",
    hour: "금1,2",
    proposer: "윤채원",
    student_affiliation: "고3",
    location: "4층 개별지도실",
    subjects: "확률과통계,미적분",
  },
  {
    id: 18,
    teacher: "조민혁",
    hojeom: "일산점",
    date: "10/11",
    hour: "토3,4",
    proposer: "서준호",
    student_affiliation: "고2",
    location: "2층 질의응답실",
    subjects: "물리1,화학1",
  },
  {
    id: 19,
    teacher: "전하늘",
    hojeom: "송파점",
    date: "10/12",
    hour: "일1,2",
    proposer: "김예은",
    student_affiliation: "고3",
    location: "3층 상담실A",
    subjects: "생명과학1,생명과학2",
  },
  {
    id: 20,
    teacher: "황지원",
    hojeom: "대치점",
    date: "10/13",
    hour: "월3,4",
    proposer: "이동훈",
    student_affiliation: "고1",
    location: "1층 멘토링실",
    subjects: "영어1,영어독해",
  },
  {
    id: 21,
    teacher: "문석진",
    hojeom: "강남점",
    date: "10/14",
    hour: "화5,6",
    proposer: "박지영",
    student_affiliation: "고3",
    location: "4층 토론실",
    subjects: "언어와매체,화법과작문",
  },
  {
    id: 22,
    teacher: "나윤서",
    hojeom: "노원점",
    date: "10/15",
    hour: "수1,2",
    proposer: "최원준",
    student_affiliation: "고2",
    location: "2층 집중학습실",
    subjects: "지구과학1,지구과학2",
  },
  {
    id: 23,
    teacher: "구본우",
    hojeom: "분당점",
    date: "10/16",
    hour: "목3,4",
    proposer: "정민아",
    student_affiliation: "고3",
    location: "3층 개별상담실",
    subjects: "윤리와사상,생활과윤리",
  },
  {
    id: 24,
    teacher: "송하은",
    hojeom: "일산점",
    date: "10/17",
    hour: "금5,6",
    proposer: "김태현",
    student_affiliation: "고1",
    location: "1층 스터디룸B",
    subjects: "한국지리,세계지리",
  },
  {
    id: 25,
    teacher: "이준석",
    hojeom: "송파점",
    date: "10/18",
    hour: "토1,2",
    proposer: "오수빈",
    student_affiliation: "고3",
    location: "4층 질의응답실",
    subjects: "수학1,수학2,미적분",
  },
  {
    id: 26,
    teacher: "최아름",
    hojeom: "대치점",
    date: "10/19",
    hour: "일3,4",
    proposer: "한지우",
    student_affiliation: "고2",
    location: "2층 개별지도실",
    subjects: "물리2,화학2",
  },
  {
    id: 27,
    teacher: "정하람",
    hojeom: "강남점",
    date: "10/20",
    hour: "월1,2",
    proposer: "신예린",
    student_affiliation: "고3",
    location: "3층 멘토링룸",
    subjects: "국어,독서,문학",
  },
  {
    id: 28,
    teacher: "노승현",
    hojeom: "노원점",
    date: "10/21",
    hour: "화3,4",
    ropser: "김하늘",
    student_affiliation: "고1",
    location: "1층 토론실",
    subjects: "영어1,영어2",
  },
  {
    id: 29,
    teacher: "권민지",
    hojeom: "분당점",
    date: "10/22",
    hour: "수5,6",
    proposer: "박성민",
    student_affiliation: "고3",
    location: "4층 집중학습실",
    subjects: "확률과통계,기하",
  },
  {
    id: 30,
    teacher: "홍석우",
    hojeom: "일산점",
    date: "10/23",
    hour: "목1,2",
    proposer: "이채은",
    student_affiliation: "고2",
    location: "2층 상담실B",
    subjects: "생물1,생물2",
  },
  {
    id: 31,
    teacher: "안소영",
    hojeom: "송파점",
    date: "10/24",
    hour: "금3,4",
    proposer: "조민우",
    student_affiliation: "고3",
    location: "3층 개별상담실",
    subjects: "사회문화,한국사",
  },
  {
    id: 32,
    teacher: "유재현",
    hojeom: "대치점",
    date: "10/25",
    hour: "토5,6",
    proposer: "강서현",
    student_affiliation: "고1",
    location: "1층 그룹상담실",
    subjects: "통합과학,과학탐구실험",
  },
  {
    id: 33,
    teacher: "임수연",
    hojeom: "강남점",
    date: "10/26",
    hour: "일1,2",
    proposer: "문지훈",
    student_affiliation: "고3",
    location: "4층 스터디룸A",
    subjects: "물리1,물리2",
  },
  {
    id: 34,
    teacher: "장현준",
    hojeom: "노원점",
    date: "10/27",
    hour: "월5,6",
    proposer: "김예지",
    student_affiliation: "고2",
    location: "2층 질의응답실",
    subjects: "화학1,지구과학1",
  },
  {
    id: 35,
    teacher: "박시온",
    hojeom: "분당점",
    date: "10/28",
    hour: "화1,2",
    proposer: "윤도현",
    student_affiliation: "고3",
    location: "3층 개별지도실",
    subjects: "언어와매체,독서",
  },
];

export const requestStatusSecondaryTemp = [
  {
    id: 1,
    teacher: "박현주 (이화여대 약대)",
    date: "5월 18일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "영어★, 국어, 화등, ...",
  },
  {
    id: 2,
    teacher: "이선형 (카톨릭대 의대)",
    date: "5월 18일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "수1/수2/미적/화등★...",
  },
  {
    id: 3,
    teacher: "이제훈 (경희대 의대)",
    date: "5월 20일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "수1/수2/미적, 화1",
  },
  {
    id: 4,
    teacher: "이충현 (성균관대 약대)",
    date: "5월 21일",
    total_number: 4,
    number_of_applications: 3,
    application_rate: "75%",
    subjects: "[수학전문] 수1/수2/...",
  },
  {
    id: 5,
    teacher: "박현주 (이화여대 약대)",
    date: "5월 25일",
    total_number: 4,
    number_of_applications: 1,
    application_rate: "25%",
    subjects: "영어★, 국어, 화등, ...",
  },
  {
    id: 6,
    teacher: "김연우 (경희대 치대)",
    date: "5월 26일",
    total_number: 4,
    number_of_applications: 2,
    application_rate: "50%",
    subjects: "국어★, 수1/수2/미...",
  },
  {
    id: 7,
    teacher: "이선형 (카톨릭대 의대)",
    date: "5월 25일",
    total_number: 4,
    number_of_applications: 2,
    application_rate: "50%",
    subjects: "수1/수2/미적/화등★...",
  },
];
